CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '唯一識別碼',
    `name` VARCHAR(255) NOT NULL UNIQUE COMMENT '使用者名稱',
    `role` TINYINT NOT NULL DEFAULT 1 COMMENT '1: general user, 2: admin',
    `password` VARCHAR(72) NOT NULL COMMENT '使用者密碼',
    `email` VARCHAR(255) NOT NULL UNIQUE COMMENT '電子郵件',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最後更新時間',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;