spring.application.name=auth
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# db setting
# write
spring.datasource.write.jdbc-url=jdbc:mysql://localhost:3306/auth?useSSL=false
spring.datasource.write.username=root
spring.datasource.write.password=mypassword
spring.datasource.write.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.write.hikari.maximum-pool-size=10

# read
spring.datasource.readonly.jdbc-url=jdbc:mysql://localhost:3306/auth?useSSL=false
spring.datasource.readonly.username=root
spring.datasource.readonly.password=mypassword
spring.datasource.readonly.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.readonly.hikari.maximum-pool-size=10

# token
jwt.secret=your-256-bit-secret-key-at-least-32-characters-long
jwt.expiration=900000