spring.application.name=
spring.mvc.throw-exception-if-no-handler-found=
spring.web.resources.add-mappings=

# db setting
# write
spring.datasource.write.jdbc-url=
spring.datasource.write.username=
spring.datasource.write.password=
spring.datasource.write.driver-class-name=
spring.datasource.write.hikari.maximum-pool-size=

# read
spring.datasource.readonly.jdbc-url=
spring.datasource.readonly.username=
spring.datasource.readonly.password=
spring.datasource.readonly.driver-class-name=
spring.datasource.readonly.hikari.maximum-pool-size=

# token
jwt.secret=
jwt.expiration=